version: "3.5"
services:
  traefik:
    image: traefik:v2.2
    volumes:
      - ./etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
networks:
  traefik:
    name: localhost-traefik
    external: true
