version: "3.5"
services:
  traefik:
    image: traefik:2.3
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - ./etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 80:80
      - 8090:8080
    networks:
      - traefik
    #labels:
    #- "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
    #- "traefik.http.routers.api.service=api@internal"
networks:
  traefik:
    name: localhost-traefik
    external: true
